spring.application.name=auth

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/microservices
spring.datasource.username=postgres
spring.datasource.password=1302
spring.jpa.hibernate.ddl-auto=update

jwt.secret=pMh8LszIdXyYvRdOHAoGut8r213d7H1mYfaV8z/V1cyVK2PavmZDz8Q8CV79vOt5OdDGdkRRiSmTv+yC82ln4A==