name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build user-service
        run: cd user-service && mvn clean package -DskipTests

      - name: Build auth-service
        run: cd auth-service && mvn clean package -DskipTests

      - name: Build api-gateway
        run: cd api-gateway && mvn clean package -DskipTests